name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    name: Exploring
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: npm build
      run: npm i
      working-directory: src

    - name: Zipping to terraform
      run: zip -r terraform/src.zip src

    - name: Initializing terraform
      run: terraform init
      working-directory: terraform


    - name: Applying terraform
      id: terraformapply
      run: terraform apply --auto-approve
      working-directory: terraform


    - name: Terraform output api gateway path
      id: terraform_output
      run: terraform output base_url
      working-directory: terraform


    - name: Getting api gateway path
      run: echo ${{ steps.terraform_output.outputs }}

    - name: Curl test
      uses: wei/curl@v1
      id: curl
      with:
        args: --data '{"username":"xyz","password":"xyz"}' https://laxzmnst1f.execute-api.eu-west-1.amazonaws.com/serverless_lambda_stage/api
