name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    name: Exploring
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: npm build
      run: cd src && npm i

    - name: Zipping to terraform
      run: zip -r terraform/src.zip src

    - name: Testing aws
      run: aws lambda list-functions

#      - run: aws --version
    - name: Initializing terraform
      run: terraform init

    - name: Applying terraform
      run: terraform apply --auto-approve
# Build docker image
#Build lambda
